version: '3.8'
services:
  dev:
    image: node:16.14
    user: "node"
    depends_on:
      - storage
    working_dir: /app
    volumes:
      - ..:/app:cached
      - ~/.npmrc:/home/node/.npmrc:delegated
    command: sleep infinity
    environment:
      - GIT_NPM_TOKEN=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

  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    environment:
      AZURITE_ACCOUNTS: 'dev:some-key'
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
