version: "3.8"

services:
  dev:
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - cosmos
    networks:
      cosmosdb-local-network:
        ipv4_address: 172.24.0.2 # 172.24.0.1 is taken by the default gateway

  storage:
    networks:
      cosmosdb-local-network:
        ipv4_address: 172.24.0.3 # 172.24.0.1 is taken by the default gateway

  cosmos:
    # Once running, the CosmosDB emulator can be accessed using a browser on the host at
    # https://localhost:8081/_explorer/index.html
    # container_name: cosmosdb-emulator
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    hostname: cosmosdb.local
    cpus: 2.0
    mem_limit: 3g
    ports:
      - 8081:8081 # Default emulator port

    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      # - AZURE_COSMOS_EMULATOR_GREMLIN_ENDPOINT=true
      - AZURE_COSMOS_EMULATOR_ENABLE_TABLE_ENDPOINT=true
    networks:
      cosmosdb-local-network:
        ipv4_address: 172.24.0.99 # using *.*.0.99 leaves some addresses for additional dependencies

# need to define explicit IPs/network as if cosmosdb IP changes the certificate will be invalid
networks:
  cosmosdb-local-network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
